# Generated by Django 3.2.11 on 2022-01-21 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('topic', models.TextField()),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
