# Generated by Django 3.2.11 on 2022-01-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(default='', max_length=10)),
                ('courseTitle', models.CharField(default='', max_length=40)),
                ('courseCredit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=30)),
                ('courseCredit', models.IntegerField()),
                ('courseGraduationYear', models.IntegerField()),
                ('courseCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(default=1, null=True)),
                ('section', models.CharField(default='A', max_length=4, null=True)),
                ('assignTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers_app.teacherslist')),
            ],
        ),
    ]
