# Generated by Django 3.2.11 on 2022-01-15 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0003_batchinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Students_app', '0008_studentsinfo_batchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropSemesterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semDropCause', models.CharField(choices=[('td', 'Temporary Drop'), ('pt', 'Program Transfer'), ('pd', 'Permanent Drop'), ('ir', 'Internship Running')], max_length=100)),
                ('dropReason', models.TextField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_drop_semester', to='Admin_panel.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_semester_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
