# Generated by Django 3.2.11 on 2022-01-15 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin_panel', '0003_batchinfo'),
        ('Students_app', '0009_dropsemestermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropsemestermodel',
            name='dropReason',
            field=models.TextField(verbose_name='Drop Reasons'),
        ),
        migrations.AlterField(
            model_name='dropsemestermodel',
            name='semDropCause',
            field=models.CharField(choices=[('td', 'Temporary Drop'), ('pt', 'Program Transfer'), ('pd', 'Permanent Drop'), ('ir', 'Internship Running')], max_length=100, verbose_name='Semester Drop Cause'),
        ),
        migrations.AlterField(
            model_name='dropsemestermodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_drop_semester', to='Admin_panel.semester', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='dropsemestermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_semester_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
