# Generated by Django 3.2.11 on 2022-01-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students_app', '0010_auto_20220116_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropsemestermodel',
            name='dropDate',
            field=models.DateField(auto_now=True),
        ),
    ]
