# Generated by Django 3.2.11 on 2022-01-16 06:09

import Students_app.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Students_app', '0011_dropsemestermodel_dropdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinfo',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Size Recommended: 512x512', keep_meta=True, quality=100, size=[512, 512], upload_to=Students_app.models.image_file_name),
        ),
    ]
