# Generated by Django 3.2.11 on 2022-01-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0003_batchinfo'),
        ('Students_app', '0014_studentapplicationmodel_applicationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplicationmodel',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_application_semester', to='Admin_panel.semester'),
            preserve_default=False,
        ),
    ]
